"""foreign key Migration

Revision ID: 3c829de941f9
Revises: e90c0c65daa3
Create Date: 2020-10-26 22:56:08.653146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c829de941f9'
down_revision = 'e90c0c65daa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dislikes', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'likes')
    op.drop_column('users', 'dislikes')
    # ### end Alembic commands ###
