"""pitch Migration

Revision ID: 47bbed6fac30
Revises: 3c829de941f9
Create Date: 2020-10-28 02:56:12.187131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47bbed6fac30'
down_revision = '3c829de941f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('dislikes', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('likes', sa.Integer(), nullable=True))
    op.drop_column('users', 'dislikes')
    op.drop_column('users', 'likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('dislikes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'likes')
    op.drop_column('pitches', 'dislikes')
    # ### end Alembic commands ###
